openapi: 3.0.0
info:
  title: Portalnesia
  description: REST API to access Portalnesia services
  version: 1.0.0
  x-logo:
    url: https://content.portalnesia.com/Banner.png
    backgroundColor: '#ffffff'
    altText: Portalnesia Logo
  termsOfService: https://portalnesia.com/pages/terms-of-service
  contact:
    name: Portalnesia
    url: https://portalnesia.com
    email: support@portalnesia.com
  license:
    name: MIT
    url: https://github.com/portalnesia/portalnesia/blob/main/LICENSE
servers:
  - url: https://api.portalnesia.com
    description: Portalnesia API Server
tags:
  - name: Authentication
  - name: Blog
  - name: Comments
  - name: Chord
  - name: Files
  - name: Geodata
  - name: Likes
  - name: Messages
  - name: Quiz
  - name: Search
  - name: Toko
  - name: Toko > Items
  - name: Toko > Transactions
  - name: Toko > Users
  - name: Tools
  - name: Tools > Downloader
  - name: Twibbon
  - name: Twitter Thread Reader
  - name: URL Shortener
  - name: Users
paths:
  /v1/blog/dashboard:
    get:
      tags:
        - Blog
      summary: Get List of My Blog
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: blog'
      security:
        - OauthUser:
            - blog
  /v1/blog:
    post:
      tags:
        - Blog
      summary: Create New Blog
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: blog'
      security:
        - OauthUser:
            - blog
    get:
      tags:
        - Blog
      summary: Get List of All Blog
      x-badges:
        - color: blue
          label: 'OAuth: Client'
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: blog'
      security:
        - OauthUser:
            - blog
        - OauthClient:
            - blog
  /v1/blog/{blog_identity}:
    put:
      tags:
        - Blog
      summary: Edit My Blog
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: blog'
      security:
        - OauthUser:
            - blog
    delete:
      tags:
        - Blog
      summary: Delete My Blog
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: blog'
      security:
        - OauthUser:
            - blog
    get:
      tags:
        - Blog
      summary: Get Blog Detail
      x-badges:
        - color: blue
          label: 'OAuth: Client'
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: blog'
      security:
        - OauthUser:
            - blog
        - OauthClient:
            - blog
  /v1/blog/tags/{tag}:
    get:
      tags:
        - Blog
      summary: Get List of Blog by Tags
      x-badges:
        - color: blue
          label: 'OAuth: Client'
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: blog'
      security:
        - OauthUser:
            - blog
        - OauthClient:
            - blog
  /v1/blog/category/{category}:
    get:
      tags:
        - Blog
      summary: Get List of Blog by Category
      x-badges:
        - color: blue
          label: 'OAuth: Client'
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: blog'
      security:
        - OauthUser:
            - blog
        - OauthClient:
            - blog
  /v1/blog/category/list:
    get:
      tags:
        - Blog
      summary: Get List of Category
      x-badges:
        - color: blue
          label: 'OAuth: Client'
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: blog'
      security:
        - OauthUser:
            - blog
        - OauthClient:
            - blog
  /v1/comments/{type}/{content_id}:
    get:
      tags:
        - Comments
      summary: Get Comments
      x-badges:
        - color: blue
          label: 'OAuth: Client'
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: comments'
      security:
        - OauthUser:
            - comments
        - OauthClient:
            - comments
    post:
      tags:
        - Comments
      summary: Create New Comment
      x-badges:
        - color: blue
          label: 'OAuth: Client'
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: comments'
      security:
        - OauthUser:
            - comments
        - OauthClient:
            - comments
  /v1/comments/{type}/{content_id}/{comment_id}:
    get:
      tags:
        - Comments
      summary: Get Replies
      x-badges:
        - color: blue
          label: 'OAuth: Client'
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: comments'
      security:
        - OauthUser:
            - comments
        - OauthClient:
            - comments
    delete:
      tags:
        - Comments
      summary: Delete Comments
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: comments'
      security:
        - OauthUser:
            - comments
  /v1/chord/dashboard:
    get:
      tags:
        - Chord
      summary: Get List of My Chord
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: chord'
      security:
        - OauthUser:
            - chord
  /v1/chord:
    get:
      tags:
        - Chord
      summary: Get List of All Chord
      x-badges:
        - color: blue
          label: 'OAuth: Client'
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: chord'
      security:
        - OauthUser:
            - chord
        - OauthClient:
            - chord
  /v1/chord/artist/{artist}:
    get:
      tags:
        - Chord
      summary: Get List of Chord by Artist
      x-badges:
        - color: blue
          label: 'OAuth: Client'
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: chord'
      security:
        - OauthUser:
            - chord
        - OauthClient:
            - chord
  /v1/chord/artist/list:
    get:
      tags:
        - Chord
      summary: Get List of All Artist
      x-badges:
        - color: blue
          label: 'OAuth: Client'
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: chord'
      security:
        - OauthUser:
            - chord
        - OauthClient:
            - chord
  /v1/chord/{slug}:
    get:
      tags:
        - Chord
      summary: Get Chord Detail
      x-badges:
        - color: blue
          label: 'OAuth: Client'
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: chord'
      security:
        - OauthUser:
            - chord
        - OauthClient:
            - chord
  /v1/files:
    get:
      tags:
        - Files
      summary: Get List of My Files
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: files'
      security:
        - OauthUser:
            - files
    post:
      tags:
        - Files
      summary: Upload Files
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: files'
      security:
        - OauthUser:
            - files
  /v1/files/{file_id}:
    get:
      tags:
        - Files
      summary: Get Files or Media Detail
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: files'
      security:
        - OauthUser:
            - files
    put:
      tags:
        - Files
      summary: Edit Files
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: files'
      security:
        - OauthUser:
            - files
    delete:
      tags:
        - Files
      summary: Delete Files
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: files'
      security:
        - OauthUser:
            - files
  /v1/geodata/epsg:
    get:
      tags:
        - Geodata
      summary: Get EPSG
      x-badges:
        - color: blue
          label: 'OAuth: Client'
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: geodata'
      security:
        - OauthUser:
            - geodata
        - OauthClient:
            - geodata
  /v1/geodata/transform-coordinates:
    post:
      tags:
        - Geodata
      summary: Transform Coordinates
      x-badges:
        - color: blue
          label: 'OAuth: Client'
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: geodata'
      security:
        - OauthUser:
            - geodata
        - OauthClient:
            - geodata
  /v1/like:
    get:
      tags:
        - Likes
      summary: Get List of My Like
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: likes'
      security:
        - OauthUser:
            - likes
  /v1/like/{type}:
    get:
      tags:
        - Likes
      summary: Get List of My Like per Type
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: likes'
      security:
        - OauthUser:
            - likes
  /v1/like/{type}/{like_id}:
    delete:
      tags:
        - Likes
      summary: Delete My Like
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: likes'
      security:
        - OauthUser:
            - likes
  /v1/messages/room:
    get:
      tags:
        - Messages
      summary: Get All Chat Room
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: messages'
      security:
        - OauthUser:
            - messages
    post:
      tags:
        - Messages
      summary: Create New Chat Room
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: messages'
      security:
        - OauthUser:
            - messages
  /v1/messages/{room_id}:
    get:
      tags:
        - Messages
      summary: Get Messages
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: messages'
      security:
        - OauthUser:
            - messages
    post:
      tags:
        - Messages
      summary: Reply Messages
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: messages'
      security:
        - OauthUser:
            - messages
  /v1/messages/{room_id}/{message_id}:
    delete:
      tags:
        - Messages
      summary: Delete Messages
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: messages'
      security:
        - OauthUser:
            - messages
  /v1/quiz:
    get:
      tags:
        - Quiz
      summary: Get List of My Quiz
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: quiz'
      security:
        - OauthUser:
            - quiz
  /v1/quiz/{quiz_id}:
    get:
      tags:
        - Quiz
      summary: Get Quiz Detail
      x-badges:
        - color: blue
          label: 'OAuth: Client'
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: quiz'
      security:
        - OauthUser:
            - quiz
        - OauthClient:
            - quiz
  /v1/search:
    get:
      tags:
        - Search
      summary: Search
      x-badges:
        - color: blue
          label: 'OAuth: Client'
        - color: red
          label: 'OAuth: User'
  /v1/search/{type}:
    get:
      tags:
        - Search
      summary: Search per Type
      x-badges:
        - color: blue
          label: 'OAuth: Client'
        - color: red
          label: 'OAuth: User'
  /v1/toko/{toko_id}/items:
    get:
      tags:
        - Toko > Items
      summary: Get List of Toko Items
      x-badges:
        - color: blue
          label: 'OAuth: Client'
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: toko'
      security:
        - OauthUser:
            - toko
        - OauthClient:
            - toko
    post:
      tags:
        - Toko > Items
      summary: Create Items
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: toko'
      security:
        - OauthUser:
            - toko
  /v1/toko/{toko_id}/items/{item_id}:
    put:
      tags:
        - Toko > Items
      summary: Edit Items
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: toko'
      security:
        - OauthUser:
            - toko
    delete:
      tags:
        - Toko > Items
      summary: Delete Items
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: toko'
      security:
        - OauthUser:
            - toko
  /v1/toko/{toko_id}/transactions:
    get:
      tags:
        - Toko > Transactions
      summary: Get List of Toko Transactions
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: toko'
      security:
        - OauthUser:
            - toko
    post:
      tags:
        - Toko > Transactions
      summary: Create New Transactions
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: toko'
      security:
        - OauthUser:
            - toko
  /v1/toko/{toko_id}/transactions/{transaction_id}:
    delete:
      tags:
        - Toko > Transactions
      summary: Delete Transactions
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: toko'
      security:
        - OauthUser:
            - toko
  /v1/toko/{toko_id}/users:
    post:
      tags:
        - Toko > Users
      summary: Add User to Toko
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: toko'
      security:
        - OauthUser:
            - toko
  /v1/toko/{toko_id}/users/{user_id}:
    put:
      tags:
        - Toko > Users
      summary: Edit User Status in Toko
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: toko'
      security:
        - OauthUser:
            - toko
    delete:
      tags:
        - Toko > Users
      summary: Delete User in Toko
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: toko'
      security:
        - OauthUser:
            - toko
  /v1/toko:
    get:
      tags:
        - Toko
      summary: Get List of My Toko
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: toko'
      security:
        - OauthUser:
            - toko
    post:
      tags:
        - Toko
      summary: Create New Toko
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: toko'
      security:
        - OauthUser:
            - toko
  /v1/toko/{toko_slug}:
    get:
      tags:
        - Toko
      summary: Get Toko Detail
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: toko'
      security:
        - OauthUser:
            - toko
    put:
      tags:
        - Toko
      summary: Edit Toko
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: toko'
      security:
        - OauthUser:
            - toko
    delete:
      tags:
        - Toko
      summary: Delete Toko
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: toko'
      security:
        - OauthUser:
            - toko
  /v1/tools/downloader/twitter:
    post:
      tags:
        - Tools > Downloader
      summary: Twitter
      x-badges:
        - color: blue
          label: 'OAuth: Client'
        - color: red
          label: 'OAuth: User'
  /v1/tools/downloader/soundcloud:
    post:
      tags:
        - Tools > Downloader
      summary: Soundcloud
      x-badges:
        - color: blue
          label: 'OAuth: Client'
        - color: red
          label: 'OAuth: User'
  /v1/tools/qr-code-generator:
    post:
      tags:
        - Tools
      summary: QR Code Generator
      description: >-
        Generate QR Code for `url`, `text`, `email`, `telephone`, `vcard`,
        `sms`, `wifi`, or `geographic` type.


        If success, this endpoint will return base64 encoded image.
      x-badges:
        - color: blue
          label: 'OAuth: Client'
        - color: red
          label: 'OAuth: User'
  /v1/tools/parse-html:
    post:
      tags:
        - Tools
      summary: Parse HTML
      x-badges:
        - color: blue
          label: 'OAuth: Client'
        - color: red
          label: 'OAuth: User'
  /v1/tools/nsfw:
    post:
      tags:
        - Tools
      summary: NSFW
      x-badges:
        - color: blue
          label: 'OAuth: Client'
        - color: red
          label: 'OAuth: User'
  /v1/twibbon/dashboard:
    get:
      tags:
        - Twibbon
      summary: Get List of My Twibbon
      x-badges:
        - color: blue
          label: 'OAuth: Client'
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: twibbon'
      security:
        - OauthUser:
            - twibbon
        - OauthClient:
            - twibbon
  /v1/twibbon:
    get:
      tags:
        - Twibbon
      summary: Get List of All Twibbon
      x-badges:
        - color: blue
          label: 'OAuth: Client'
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: twibbon'
      security:
        - OauthUser:
            - twibbon
        - OauthClient:
            - twibbon
  /v1/twibbon/{slug}:
    get:
      tags:
        - Twibbon
      summary: Get Twibbon Detail
      x-badges:
        - color: blue
          label: 'OAuth: Client'
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: twibbon'
      security:
        - OauthUser:
            - twibbon
        - OauthClient:
            - twibbon
    put:
      tags:
        - Twibbon
      summary: Edit Twibbon
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: twibbon'
      security:
        - OauthUser:
            - twibbon
    delete:
      tags:
        - Twibbon
      summary: Delete Twibbon
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: twibbon'
      security:
        - OauthUser:
            - twibbon
  /v1/twitter/thread:
    get:
      tags:
        - Twitter Thread Reader
      summary: Get List of Threads
      x-badges:
        - color: blue
          label: 'OAuth: Client'
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: thread'
      security:
        - OauthUser:
            - thread
        - OauthClient:
            - thread
    post:
      tags:
        - Twitter Thread Reader
      summary: New Thread
      x-badges:
        - color: blue
          label: 'OAuth: Client'
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: thread'
      security:
        - OauthUser:
            - thread
        - OauthClient:
            - thread
  /v1/twitter/thread/{tweet_id}:
    get:
      tags:
        - Twitter Thread Reader
      summary: Get Thread Detail
      x-badges:
        - color: blue
          label: 'OAuth: Client'
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: thread'
      security:
        - OauthUser:
            - thread
        - OauthClient:
            - thread
    post:
      tags:
        - Twitter Thread Reader
      summary: Update Tweet in Thread
      x-badges:
        - color: blue
          label: 'OAuth: Client'
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: thread'
      security:
        - OauthUser:
            - thread
        - OauthClient:
            - thread
  /v1/url-shortener:
    post:
      tags:
        - URL Shortener
      summary: New URL Shortener
      x-badges:
        - color: blue
          label: 'OAuth: Client'
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: url-shortener'
      security:
        - OauthUser:
            - url-shortener
        - OauthClient:
            - url-shortener
    get:
      tags:
        - URL Shortener
      summary: Get List of My URL
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: url-shortener'
      security:
        - OauthUser:
            - url-shortener
  /v1/url-shortener/{id}:
    delete:
      tags:
        - URL Shortener
      summary: Delete My URL
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: url-shortener'
      security:
        - OauthUser:
            - url-shortener
  /v1/user:
    get:
      tags:
        - Users
      summary: Get Basic Profile
      description: >-
        Get basic user profile that related to the **Access Token**.   


        **Note**: Response will return an email, if your access token has
        `email` scope.
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: email'
      security:
        - OauthUser:
            - email
  /v1/user/{username}:
    get:
      tags:
        - Users
      summary: Get Profile of Username
      x-badges:
        - color: blue
          label: 'OAuth: Client'
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: user'
      security:
        - OauthUser:
            - user
        - OauthClient:
            - user
    post:
      tags:
        - Users
      summary: Change Profile Picture
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: user'
      security:
        - OauthUser:
            - user
    delete:
      tags:
        - Users
      summary: Remove Profile Picture
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: user'
      security:
        - OauthUser:
            - user
    put:
      tags:
        - Users
      summary: Edit Profile
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: user'
      security:
        - OauthUser:
            - user
  /v1/user/{username}/followers:
    get:
      tags:
        - Users
      summary: Get List of Followers
      x-badges:
        - color: blue
          label: 'OAuth: Client'
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: user'
      security:
        - OauthUser:
            - user
        - OauthClient:
            - user
  /v1/user/{username}/followers/pending:
    get:
      tags:
        - Users
      summary: Get List of Pending Followers
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: user'
      security:
        - OauthUser:
            - user
  /v1/user/{username}/followers/pending/{token}:
    post:
      tags:
        - Users
      summary: Accept Pending Followers
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: user'
      security:
        - OauthUser:
            - user
    delete:
      tags:
        - Users
      summary: Decline Pending Follower
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: user'
      security:
        - OauthUser:
            - user
  /v1/user/{username}/following:
    get:
      tags:
        - Users
      summary: Get List of Following
      x-badges:
        - color: blue
          label: 'OAuth: Client'
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: user'
      security:
        - OauthUser:
            - user
        - OauthClient:
            - user
  /v1/user/{username}/following/{target_username}:
    post:
      tags:
        - Users
      summary: Follow User
      description: >-
        Allows the authenticated user to follow another user.


        If the target user is private, this endpoint will send a follow request.


        The request succeeds with no action when the authenticated user sends a
        request to a user they're already following, or if they're sending a
        follower request to a private user and that user has not accepted the
        friend request.
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: user'
      security:
        - OauthUser:
            - user
    delete:
      tags:
        - Users
      summary: Unfollow User
      description: >-
        Allows the authenticated user to unfollow another user.


        The request succeeds with no action when the authenticated user sends a
        request to a user they're not following or have already unfollowed.
      x-badges:
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: user'
      security:
        - OauthUser:
            - user
  /v1/user/{username}/media:
    get:
      tags:
        - Users
      summary: Get List of Media
      x-badges:
        - color: blue
          label: 'OAuth: Client'
        - color: red
          label: 'OAuth: User'
        - color: yellow
          label: 'Scope: user'
        - color: yellow
          label: 'Scope: files'
      security:
        - OauthUser:
            - user
            - files
        - OauthClient:
            - user
            - files
security:
  - OauthUser:
      - basic
  - OauthClient:
      - basic
components:
  securitySchemes:
    OauthUser:
      type: oauth2
      description: >-
        OAuth2 with user based authentication that include user authorization.
        With this authentication, you can access all of the endpoints,
        especially endpoints that can access user resources.
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.portalnesia.com/oauth/authorize
          refreshUrl: https://accounts.portalnesia.com/oauth/token
          tokenUrl: https://accounts.portalnesia.com/oauth/token
          scopes:
            basic: Basic access to endpoint.
            email: Get user email
            blog: Access blog endpoint, have read and write access to user's blog
            comments: >-
              Access comments endpoint, have read and write access to user's
              comments
            chord: Access chord endpoint
            files: Access files endpoint, have read and write access to user's files
            geodata: Access geodata endpoint
            likes: Access likes endpoint, have read and write access to user's likes
            messages: >-
              Access messages endpoint, have read and write access to user's
              messages
            toko: Access toko endpoint, have read and write access to user's toko
            twibbon: >-
              Access twibbon endpoint, have read and write access to user's
              twibbon
            thread: Access twitter thread endpoint
            url-shortener: >-
              Access url shortener endpoint, have read and write access to
              user's url shortener
            user: >-
              Access user endpoint, have read and write access to user's
              following, follower, profile, media
    OauthClient:
      type: oauth2
      description: >-
        OAuth2 with client based authentication. This flow is used in
        **server-to-server** authentication.   

        Since this flow does not include authorization, ONLY endpoints that do
        not access user information can be accessed.
      flows:
        clientCredentials:
          tokenUrl: https://accounts.portalnesia.com/oauth/token
          refreshUrl: https://accounts.portalnesia.com/oauth/token
          scopes:
            basic: Basic read access.
            blog: Read access to blog endpoint
            chord: Read access to chord endpoint
            comments: Read access to comments endpoint
            geodata: Access to geodata endpoint
            twibbon: Read access to twibbon endpoint
            thread: Access to twitter thread endpoint
            toko: Read access to toko items
            url-shortener: Access to url shortener endpoint
            user: Read access to user endpoint

